### ISSUE TITLE
Problem with Notes

### ISSUE THREAD

**Issue by zeteticl** [ernieayala/ernies-modern-layout#176] opened 2022-10-04 07:07 UTC
Without Modern UI
![image](https://user-images.githubusercontent.com/23254376/193755559-b4037c8c-3464-4a98-9522-1fbe0a1f11a2.png)

With Modern UI
when mouse touch the title, the text will disappear
![image](https://user-images.githubusercontent.com/23254376/193755725-e2bd4711-89bc-4e07-a7b5-545a71ea0ca4.png)

and the title  offset to top
![image](https://user-images.githubusercontent.com/23254376/193756272-a613f7e5-989d-44e9-87ad-b48218c09cfc.png)

**Comment by ernieayala** [comment] 2022-12-20 21:45
![Screenshot 2022-12-20 134513](https://user-images.githubusercontent.com/9342233/208773012-57c6ac31-9832-4c38-a876-499bbd2bc7ba.png)
 
Not able to reproduce. Might be fixed in latest.

**Closed** 2022-12-21 00:03 UTC
Labels: investigate
